### ISSUE TITLE
格式化时不要为text标签内容加上换行，否则导致页面排版错乱

### ISSUE THREAD

**Issue by wjf2016** [cnyballk/wxml-vscode#4]
格式化时不要为text标签内容加上换行，否则导致页面排版错乱。

 可以参考minapp扩展针对这个问题的解决方法：
https://marketplace.visualstudio.com/items?itemName=qiu8310.minapp-vscode
【2018-08-06】1.7.2 添加配置项 reserveTags，表示不格式化此配置中的 tag 标签的内容（一般 text 标签不需要格式化）

**Comment by cnyballk** [comment]
没有问题，明天搞

**Comment by cnyballk** [comment]
已添加 unformatted 属性默认不格式化 text 标签

**Comment by LeonHugo** [comment]
为什么我加了"unformatted": "['text']", text标签还是会格式化换行呢？
