### ISSUE TITLE
增加一个设置选项：无子元素时是否闭合标签

### ISSUE THREAD

**Issue by wjf2016** [cnyballk/wxml-vscode#5]
增加一个设置选项：无子元素时是否闭合标签。因为有时候在写页面结构的时候，暂时不写里面的内容，但是一格式化的话就变成闭合标签了，下次想要增加标签内容时就麻烦了，要手动修改，还要手动加上闭合标签。希望加一个设置选项，无子元素时是否闭合标签:false/true，灵活控制。

**Comment by cnyballk** [comment]
没有问题

**Comment by cnyballk** [comment]
已添加[ disable_automatic_closing_labels ](https://github.com/cnyballk/wxml-vscode/blob/master/CHANGELOG.md#006)属性
