### ISSUE TITLE
0.0.6版本，{{}} 中的空白在格式化或编辑器获得焦点时变大

### ISSUE THREAD

**Issue by wjf2016** [cnyballk/wxml-vscode#7]
举例：
原始代码：<camel-order-detail-info data="{{orderDetailInfo}}" />

代码不做任何改动，只是重复“保存”和“使编辑器获得焦点”的操作，多次操作后{{}}之间的空白变大了，变成以下这种情况：
<camel-order-detail-info data="{{                        orderDetailInfo                        }}" />

还有这个问题：
原代码：
	<camel-detail-contact
	 wx:if="{{  kf_service == 0 && l_kefu_lon  }}"
	 userInfo='{{  user_Info  }}'
	 sendMessagePath="/pages/account/orderDetail/index?id={{  orderInfo.id  }}"
	/>
格式化后：
	<camel-detail-contact
	 wx:if="{{  kf_service == 0 && l_kefu_lon  }}"
	 userInfo='{{  user_Info  }}'
	 sendMessagePath="/pages/account/orderDetail/index ? id={{  orderInfo.id  }}"
	/>
即：格式化后sendMessagePath属性中?前后被加上空格了

**Comment by cnyballk** [comment]
好的，我会看看的

**Comment by ThorWu** [comment]
+1

**Comment by cnyballk** [comment]
问题已修复，并发布了 v0.1.0版本，可查看[CHANGELOG.md](https://github.com/cnyballk/wxml-vscode/blob/master/CHANGELOG.md#010)
